version: '3'

services:

  caddy:
    image: arkadiyagapov/erg-survey-caddy:1.0.21
    deploy:
      mode: global
    ports:
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: