version: '3'

services:

  front-service:
    image: arkadiyagapov/erg-survey-front:1.0.0
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  back-service:
    image: arkadiyagapov/erg-survey-back:1.0.0
    restart: always
    deploy:
      mode: replicated
      replicas: 1

  caddy:
    image: arkadiyagapov/erg-survey-caddy:1.0.0
    deploy:
      mode: global
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: