version: '3'

services:

  front-service:
    build:
      context: ./../front
      dockerfile: ./../front/erg.survey.front.dockerfile
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  back-service:
    build:
      context: ./../back
      dockerfile: ./../back/erg.survey.back.dockerfile
    restart: always
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1

  caddy:
    build:
      context: ./
      dockerfile: ./caddy.dockerfile
    deploy:
      mode: global
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
    external: true
  caddy_config: