version: '3'

services:

  front-service:
    image: arkadiyagapov/erg-survey-front:1.0.2
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "80:8080"

  back-service:
    image: arkadiyagapov/erg-survey-back:1.0.2
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "8081:8081"