version: '3'

services:

  front-end-service:
    image: arkadiyagapov/erg-survey-front:1.0.0
    restart: always
    ports:
      - "8080:8080"
    deploy:
      mode: replicated
      replicas: 1

  back-end-service:
    image: arkadiyagapov/erg-survey-back:1.0.0
    restart: always
    ports:
      - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1